# Generated by Django 3.2.8 on 2024-01-13 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblib', '0002_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
