# Generated by Django 3.2.8 on 2024-01-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblib', '0003_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.TextField(default='J.K Rowling', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.TextField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='/-', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.TextField(default='/-', max_length=100),
        ),
    ]
